title: 5G-AMM
lang: kr
description: 엣지 브레인 프레임워크 기반 스마트 공장의 주행, 조작, 작업을 위한 모바일 매니퓰레이팅 기술개발

remote_theme: rundocs/jekyll-rtd-theme

# debug:
#   compress: false
#   dist: false
#   extension: true

readme_index:
  with_frontmatter: true

sass:
  style: compress

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec
